#pragma once

// it's easier this way.

#define datapath_icon "./data/icon.png"
#define datapath_vignette "./data/vignette.png"
#define datapath_intro "./data/intro.png"
#define datapath_menu_opt_01 "./data/menu_opt_01.png"
#define datapath_menu_opt_02 "./data/menu_opt_02.png"
#define datapath_menu_opt_03 "./data/menu_opt_03.png"
#define datapath_menu_opt_04 "./data/menu_opt_04.png"
#define datapath_menu_block "./data/menu_block.png"
#define datapath_instr "./data/instr.png"
#define datapath_rec_back "./data/rec_back.png"
#define datapath_menu_opt_01_s "./data/menu_opt_01_s.png"
#define datapath_menu_opt_02_s "./data/menu_opt_02_s.png"
#define datapath_menu_opt_03_s "./data/menu_opt_03_s.png"
#define datapath_background_01 "./data/background_01.png"
#define datapath_block "./data/block.png"
#define datapath_person "./data/person.png"
#define datapath_person_f01 "./data/person_f01.png"
#define datapath_person_f02 "./data/person_f02.png"
#define datapath_dark_01 "./data/dark_01.png"
#define datapath_dark_02 "./data/dark_02.png"
#define datapath_dark_03 "./data/dark_03.png"
#define datapath_pause_continue "./data/pause_continue.png"
#define datapath_pause_exit "./data/pause_exit.png"
#define datapath_saving_score "./data/saving_score.png"
#define datapath_block_end "./data/block_end.png"

#define datapath_DejaVuSans "./data/DejaVuSans.ttf"